version: '3.7'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timetable
    ports:
      - '5432:5432'

  smtp:
    image: namshi/smtp
    container_name: smtp
    ports:
      - '25:25'