server:
  port: 8081

spring:
  datasource:
    platform: postgres:latest
    url: jdbc:postgresql://localhost:5432/timetable
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  ldap:
    embedded:
      port: 389
      ldif: classpath:ldap-data.ldif
      base-dn: o=huszarotilia,c=com
      credential:
        username: uid=admin
        password: password

institution:
  name: UBB
  description: Universitatea Babes-Bolyai Cluj-Napoca
  foundedIn: 1959
  website: https://www.ubbcluj.ro/

jwt:
  secret: jWtS3cR3t
  expirationInMillis: 3600000 # 1 hour